#%RAML 1.0
title: Accounts API
version: v1

/accounts:
  get: 
    
    responses:
      200:
        body:
          application/json:
            example:
              {
                accID: "101",
                accountName: "ADM"

              }
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
                    
        